apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-config-{{ .Values.evaluationConfig.jobName }}
  {{- if .Values.evaluationConfig.namespace }}
  namespace: {{ .Values.evaluationConfig.namespace }}
  {{- end }}
  labels:
    app: {{ .Values.evaluationConfig.jobName }}
    {{- if .Values.evaluationConfig.customLabels }}
    {{- toYaml .Values.evaluationConfig.customLabels | nindent 4 }}
    {{- end }}
data:
  recipe.yaml: |
{{ (.Files.Get "config/{{ .Values.evaluationConfig.jobName }}_hydra.yaml") | indent 4 }}
